# Generated by Django 4.1 on 2023-03-04 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_filial', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('nbm', models.CharField(max_length=255, verbose_name='nbm')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255, null=True, verbose_name='Status')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='admins.userinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name')),
                ('bith_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('nbm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nbm')),
                ('sex', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=255, null=True, verbose_name='Sex')),
                ('education', models.CharField(blank=True, choices=[('Oliy', 'Oliy'), ('Orta', 'Orta')], max_length=255, null=True, verbose_name='Education')),
                ('family_status', models.CharField(blank=True, choices=[('Some', 'Some')], max_length=255, null=True, verbose_name='Family status')),
                ('child_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Child count')),
                ('spouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spouse')),
                ('spouse_birth_date', models.DateField(blank=True, null=True)),
                ('spouse_education', models.CharField(blank=True, choices=[('Oliy', 'Oliy'), ('Orta', 'Orta')], max_length=255, null=True)),
                ('oper_date', models.DateTimeField(blank=True, null=True)),
                ('agent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Yangi mijoz', 'Yangi mijoz'), ('Operator qabul qildi', 'Operator qabul qildi'), ('Mijozga aloqaga chiqildi', 'Mijozga aloqaga chiqildi'), ('To‘lov qilindi', 'To‘lov qilindi'), ('Operator tomonidan bekor qilish', 'Operator tomonidan bekor qilish'), ('GreenCard oldi', 'GreenCard oldi'), ('GreenCard tomonidan bekor qilindi', 'GreenCard tomonidan bekor qilindi')], default='Yangi mijoz', max_length=255, verbose_name='Status')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_users', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='admins.userinfo')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='client_images')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admins.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_fiels')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admins.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('text', models.TextField()),
                ('cliet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admins.clients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
