# Generated by Django 4.1 on 2023-03-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_userinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='family_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Family status'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
