# Generated by Django 4.1 on 2023-03-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_clients_family_status_alter_userinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='admins.userinfo'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='spouse_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
