# Generated by Django 4.1 on 2023-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_clients_filial_alter_clients_spouse_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcomments',
            name='date',
            field=models.DateTimeField(auto_created=True, verbose_name='Date'),
        ),
    ]
