# Generated by Django 4.1 on 2023-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_clientcomments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
