# Generated by Django 4.1 on 2023-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_clientcomments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(blank=True, choices=[('Yangi mijoz', 'Yangi mijoz'), ('Operator qabul qildi', 'Operator qabul qildi'), ('Mijozga aloqaga chiqildi', 'Mijozga aloqaga chiqildi'), ('To‘lov qilindi', 'To‘lov qilindi'), ('Operator tomonidan bekor qilish', 'Operator tomonidan bekor qilish'), ('GreenCard oldi', 'GreenCard oldi'), ('GreenCard tomonidan bekor qilindi', 'GreenCard tomonidan bekor qilindi')], default='Yangi mijoz', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
