# Generated by Django 4.1 on 2023-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Boydoq', 'Boydoq'), ('Uylangan', 'Uylangan'), ('Turmishga chiqgan', 'Turmishga chiqgan')], max_length=255, null=True, verbose_name='Family status'),
        ),
    ]
