# Generated by Django 4.1 on 2023-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_clients_family_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='bith_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='child_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Child count'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='spouse_birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
