# Generated by Django 4.1 on 2023-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_clients_bith_date_alter_clients_child_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(blank=True, choices=[('recieved', 'Yangi mijoz'), ('recieved', 'Operator qabul qildi'), ('contacted', 'Mijozga aloqaga chiqildi'), ('paid', 'To‘lov qilindi'), ('cancelled', 'Operator tomonidan bekor qilish'), ('accepted', 'GreenCard oldi'), ('rejected', 'GreenCard tomonidan bekor qilindi')], default='Yangi mijoz', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
