# Generated by Django 4.1 on 2023-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Yangi mijoz'), ('recieved', 'Operator qabul qildi'), ('contacted', 'Mijozga aloqaga chiqildi'), ('paid', 'To‘lov qilindi'), ('cancelled', 'Operator tomonidan bekor qilish'), ('accepted', 'GreenCard oldi'), ('rejected', 'GreenCard tomonidan bekor qilindi')], default='new', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
