# Generated by Django 4.1 on 2023-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_alter_clients_child_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='birth_adres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth adress'),
        ),
    ]
