# Generated by Django 4.1 on 2023-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_clients_spouse_adres_clients_spouse_birth_adres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='sex',
            field=models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=255, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='spouse_sex',
            field=models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Ayol', max_length=255, null=True, verbose_name='Sex'),
        ),
    ]
